### ISSUE TITLE
Feature Request: Support Light Groups

### ISSUE THREAD

**Issue by Gibby** [rmonty/IntelliCenterControl#1]
Support light groups for changing colors, syncing and setting to swim.

**Comment by Gibby** [comment]
@rmonty the partial integration you did so far is perfect!

**Comment by rmonty** [comment]
thanks, will work on getting some more integrated, just have to figure out the layout as there is limited room on the control screen.  I am thinking it may be a pop-up window for color control, sync, swim, etc.

**Comment by rmonty** [comment]
Finished integration in latest build.  Should be rolling out from Google Play soon.  Re-open issue if it isn't what you expected or doesn't work correctly for you.
