### ISSUE TITLE
Feature Request: Support Solar Sensor

### ISSUE THREAD

**Issue by Gibby** [rmonty/IntelliCenterControl#2]
Support reading temperature of the solar sensor.

**Comment by rmonty** [comment]
Do you want it squeezed in with the other sensors or would you rather have another tab with all sensors?

**Comment by Gibby** [comment]
@rmonty sorry I didn't respond in time. I just checked the app and your implementation perfect!

Granted, I don't use the solar sensor for anything, but as much as you can replicate in from the Pentair app the better. This is 1000000% better than Pentair's.
